# Generated by Django 2.1.3 on 2018-11-25 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Eleve',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_et', models.CharField(max_length=42, verbose_name='Eleve')),
                ('num', models.CharField(max_length=15, null=True, verbose_name='Telephone Eleve')),
                ('email', models.EmailField(max_length=254, null=True, verbose_name='E-mail')),
                ('date_naissance', models.DateField(null=True)),
                ('etablissement', models.CharField(max_length=20, null=True)),
            ],
            options={
                'verbose_name': 'eleve',
            },
        ),
        migrations.CreateModel(
            name='Lieu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('adresse', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=42)),
                ('num_tel', models.CharField(max_length=15)),
                ('mail', models.EmailField(max_length=254)),
                ('adresse', models.CharField(max_length=150)),
                ('estResponsable', models.BooleanField()),
                ('date_inscription', models.DateField(auto_now=True, verbose_name="Date d'inscription")),
            ],
            options={
                'verbose_name': 'parent',
            },
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('lieu_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='TGA_tool.Lieu')),
                ('menu', models.TextField()),
                ('lieu_spe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='special', to='TGA_tool.Lieu')),
            ],
            bases=('TGA_tool.lieu',),
        ),
        migrations.AddField(
            model_name='eleve',
            name='parent_resp',
            field=models.ForeignKey(limit_choices_to={'estResponsable': True}, on_delete=django.db.models.deletion.CASCADE, to='TGA_tool.Parent', verbose_name='Parent responsable'),
        ),
        migrations.AddField(
            model_name='eleve',
            name='parent_sec',
            field=models.ForeignKey(limit_choices_to={'estResponsable': False}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secondaire', to='TGA_tool.Parent', verbose_name='Parent contact'),
        ),
    ]
