# Generated by Django 2.1.7 on 2019-04-11 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TGA_tool', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payement',
            name='parent',
        ),
        migrations.AddField(
            model_name='payement',
            name='client',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='TGA_tool.Client', verbose_name='Client'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='parent',
            name='famille',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TGA_tool.Famille', verbose_name='Famille'),
        ),
    ]
