# Generated by Django 2.1.3 on 2018-11-25 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TGA_tool', '0002_groupe'),
    ]

    operations = [
        migrations.AddField(
            model_name='eleve',
            name='Groupe',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='TGA_tool.Groupe'),
            preserve_default=False,
        ),
    ]
