# Generated by Django 2.1.3 on 2018-12-06 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TGA_tool', '0002_auto_20181202_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='disponibilité',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='eleve',
            name='cours',
            field=models.ManyToManyField(blank=True, related_name='cours', to='TGA_tool.Cours', verbose_name='Cours'),
        ),
        migrations.AlterField(
            model_name='frequence',
            name='frequence',
            field=models.CharField(choices=[('OS', 'Une seule fois'), ('Par semaine', 'Chaque semaine'), ('Par mois', 'Chaque mois'), ('Par jour', 'Chaque jour')], default='OS', max_length=11, verbose_name='Fréquence'),
        ),
        migrations.AlterField(
            model_name='salle',
            name='disponibilité',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
