# Generated by Django 2.1.7 on 2019-04-11 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TGA_tool', '0003_auto_20190411_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='famille',
            name='adresse',
            field=models.CharField(max_length=100, verbose_name='Adresse de famille'),
        ),
    ]
