# Generated by Django 2.1.3 on 2018-12-10 23:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TGA_tool', '0003_creneau_fin'),
    ]

    operations = [
        migrations.AddField(
            model_name='frequence',
            name='creneau',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='TGA_tool.Creneau', verbose_name='Creneau'),
        ),
        migrations.AlterField(
            model_name='seance',
            name='creneau',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TGA_tool.Creneau', verbose_name='Creneau'),
        ),
    ]
