# Generated by Django 2.1.7 on 2019-04-09 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TGA_tool', '0003_auto_20190409_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elevepotentiel',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail'),
        ),
    ]
