# Generated by Django 2.1.3 on 2018-12-06 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TGA_tool', '0003_auto_20181206_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frequence',
            name='frequence',
            field=models.CharField(choices=[('Une séance', 'Une séance'), ('Séances par semaine', 'Chaque semaine'), ('Séances par mois', 'Chaque mois'), ('Séances par jour', 'Chaque jour'), ('Une séance par quinzaine', 'Une séance par quinzaine')], default='OS', max_length=11, verbose_name='Fréquence'),
        ),
        migrations.AlterField(
            model_name='seance',
            name='creneau',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Creneau'),
        ),
    ]
