# Generated by Django 2.1.3 on 2018-12-11 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TGA_tool', '0004_auto_20181211_0020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='frequence',
            name='intervalle',
        ),
        migrations.AddField(
            model_name='frequence',
            name='period',
            field=models.PositiveIntegerField(blank=True, help_text="Periodicité dans l'intervalle de temps", null=True, verbose_name='Chaque'),
        ),
    ]
