# Generated by Django 2.1.3 on 2018-12-07 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TGA_tool', '0005_auto_20181207_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='seance',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='seance',
            name='creneau',
            field=models.TimeField(blank=True, null=True, verbose_name='Creneau'),
        ),
    ]
