# Generated by Django 2.1.7 on 2019-04-11 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TGA_tool', '0005_auto_20190411_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='sessions',
            field=models.ManyToManyField(blank=True, through='TGA_tool.Requete', to='TGA_tool.Session', verbose_name='Cours potentiels demandes'),
        ),
    ]
