# Generated by Django 2.1.3 on 2018-12-16 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TGA_tool', '0006_auto_20181216_2331'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seance_Coaching',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Date')),
                ('chapitre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='TGA_tool.Chapitre', verbose_name='Chapitre')),
                ('creneau', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TGA_tool.Creneau', verbose_name='Creneau')),
                ('eleve', models.ManyToManyField(blank=True, related_name='eleve_coaching', to='TGA_tool.Eleve')),
                ('matiere', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TGA_tool.Matiere')),
                ('notions', models.ManyToManyField(blank=True, related_name='tga_tool_seance_coaching_related', to='TGA_tool.Notions', verbose_name='Notions')),
                ('salle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='TGA_tool.Salle', verbose_name='Salle')),
            ],
            options={
                'verbose_name': 'seance coaching',
            },
        ),
        migrations.CreateModel(
            name='Seance_Cours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Date')),
                ('statut', models.CharField(choices=[('PL', 'Planifiée'), ('EF', 'Effectuée'), ('AN', 'Annulée')], default='PL', max_length=2, verbose_name='Statut')),
                ('chapitre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='TGA_tool.Chapitre', verbose_name='Chapitre')),
                ('cours', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TGA_tool.Cours', verbose_name='Cours')),
                ('creneau', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TGA_tool.Creneau', verbose_name='Creneau')),
                ('notions', models.ManyToManyField(blank=True, related_name='tga_tool_seance_cours_related', to='TGA_tool.Notions', verbose_name='Notions')),
                ('salle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='TGA_tool.Salle', verbose_name='Salle')),
            ],
            options={
                'verbose_name': 'seance cours',
            },
        ),
    ]
