# Generated by Django 2.1.3 on 2018-12-07 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TGA_tool', '0006_auto_20181207_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seance',
            name='cours',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TGA_tool.Cours', verbose_name='Cours'),
        ),
    ]
