# Generated by Django 2.1.7 on 2019-04-11 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TGA_tool', '0006_auto_20190411_1307'),
    ]

    operations = [
        migrations.RenameField(
            model_name='langue',
            old_name='niveau',
            new_name='langue',
        ),
        migrations.RemoveField(
            model_name='langue',
            name='programme',
        ),
        migrations.AddField(
            model_name='elevepotentiel',
            name='Prenom',
            field=models.CharField(default='', max_length=42, verbose_name='Prenom'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cours',
            name='langue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='langue_du_cours', to='TGA_tool.Langue', verbose_name='Langue'),
        ),
        migrations.AlterField(
            model_name='elevepotentiel',
            name='nom',
            field=models.CharField(max_length=42, verbose_name='Nom'),
        ),
    ]
