# Generated by Django 2.1.3 on 2018-11-25 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TGA_tool', '0006_auto_20181125_1622'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='lieu_ptr',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='lieu_spe',
        ),
        migrations.DeleteModel(
            name='Lieu',
        ),
        migrations.DeleteModel(
            name='Restaurant',
        ),
    ]
