# Generated by Django 2.1.3 on 2018-11-26 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TGA_tool', '0007_auto_20181126_0041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eleve',
            name='Groupe',
        ),
        migrations.AddField(
            model_name='eleve',
            name='groupe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='TGA_tool.Groupe'),
        ),
    ]
