# Generated by Django 2.1.3 on 2018-12-17 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TGA_tool', '0007_seance_coaching_seance_cours'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chapitre',
            options={'ordering': ['matiere', 'chapitre'], 'verbose_name': 'chapitre'},
        ),
        migrations.AlterModelOptions(
            name='coach',
            options={'ordering': ['nom'], 'verbose_name': 'coach'},
        ),
        migrations.AlterModelOptions(
            name='cours',
            options={'ordering': ['-curriculum', 'matiere'], 'verbose_name': 'cours'},
        ),
        migrations.AlterModelOptions(
            name='eleve',
            options={'ordering': ['nom'], 'verbose_name': 'eleve'},
        ),
        migrations.AlterModelOptions(
            name='notions',
            options={'ordering': ['chapitre', 'details'], 'verbose_name': 'notions'},
        ),
        migrations.AlterModelOptions(
            name='parent',
            options={'ordering': ['nom'], 'verbose_name': 'parent'},
        ),
        migrations.AlterModelOptions(
            name='salle',
            options={'ordering': ['capcite'], 'verbose_name': 'salle'},
        ),
        migrations.AlterModelOptions(
            name='seance_coaching',
            options={'ordering': ['date', 'creneau'], 'verbose_name': 'seance coaching'},
        ),
        migrations.AlterModelOptions(
            name='seance_cours',
            options={'ordering': ['date', 'creneau'], 'verbose_name': 'seance cours'},
        ),
        migrations.AddField(
            model_name='chapitre',
            name='details',
            field=models.TextField(blank=True, help_text='Précisions sur le chapitre', null=True),
        ),
        migrations.AlterField(
            model_name='coach',
            name='mail',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='coach',
            name='matieres',
            field=models.ManyToManyField(help_text='Les matières que peut enseigner ce coach', related_name='enseigne', to='TGA_tool.Matiere', verbose_name='matieres'),
        ),
        migrations.AlterField(
            model_name='coach',
            name='telphone',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True, verbose_name='Telephone'),
        ),
        migrations.AlterField(
            model_name='cours',
            name='curriculum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curriculum', to='TGA_tool.Curriculum', verbose_name='Curriculum'),
        ),
        migrations.AlterField(
            model_name='cours',
            name='matiere',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TGA_tool.Matiere', verbose_name='Matiere'),
        ),
        migrations.AlterField(
            model_name='curriculum',
            name='programme',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='eleve',
            name='date_naissance',
            field=models.DateField(blank=True, null=True, verbose_name='Date de naissance'),
        ),
        migrations.AlterField(
            model_name='eleve',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='eleve',
            name='etablissement',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='eleve',
            name='nom',
            field=models.CharField(max_length=42, unique=True, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='eleve',
            name='num',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True, verbose_name='Telephone'),
        ),
        migrations.AlterField(
            model_name='parent',
            name='adresse',
            field=models.CharField(blank=True, max_length=150, verbose_name='Adresse'),
        ),
        migrations.AlterField(
            model_name='parent',
            name='mail',
            field=models.EmailField(blank=True, max_length=254, unique=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='salle',
            name='capcite',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Capacité'),
        ),
        migrations.AlterField(
            model_name='seance_cours',
            name='cours',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='TGA_tool.Cours', verbose_name='Cours'),
            preserve_default=False,
        ),
    ]
