# Generated by Django 2.1.3 on 2018-12-07 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TGA_tool', '0007_auto_20181207_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frequence',
            name='frequence',
            field=models.CharField(choices=[('Frequence', (('Une seance', 'Une séance'), ('Chaque jour', 'Chaque jour'), ('Chaque jour de la semaine', 'Chaque jour de la semaine'), ('Chaque jour du mois', "Chaque 'jour' du mois"))), ('Personalisé', (('Jours', 'Chaque x jours'), ('Semaines', 'Chaque x semaines'), ('Mois', 'Chaque x mois')))], default='Une seance', max_length=30, verbose_name='Fréquence'),
        ),
        migrations.AlterField(
            model_name='frequence',
            name='jour',
            field=models.PositiveIntegerField(blank=True, choices=[(7, 'Dimanche'), (1, 'Lundi'), (2, 'Mardi'), (3, 'Mercredi'), (4, 'Jeudi'), (5, 'Vendredi'), (6, 'Samedi')], null=True),
        ),
    ]
