# Generated by Django 2.1.7 on 2019-04-12 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TGA_tool', '0007_auto_20190411_1701'),
    ]

    operations = [
        migrations.RenameField(
            model_name='elevepotentiel',
            old_name='Prenom',
            new_name='prenom',
        ),
    ]
