# Generated by Django 2.1.3 on 2018-12-20 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TGA_tool', '0008_auto_20181217_2233'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coach',
            options={'verbose_name': 'coach'},
        ),
        migrations.AlterModelOptions(
            name='eleve',
            options={'verbose_name': 'eleve'},
        ),
        migrations.AlterModelOptions(
            name='parent',
            options={'verbose_name': 'parent'},
        ),
        migrations.RemoveField(
            model_name='coach',
            name='mail',
        ),
        migrations.RemoveField(
            model_name='coach',
            name='nom',
        ),
        migrations.RemoveField(
            model_name='eleve',
            name='email',
        ),
        migrations.RemoveField(
            model_name='eleve',
            name='nom',
        ),
        migrations.RemoveField(
            model_name='parent',
            name='mail',
        ),
        migrations.RemoveField(
            model_name='parent',
            name='nom',
        ),
    ]
