# Generated by Django 2.1.7 on 2019-04-12 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TGA_tool', '0008_auto_20190412_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='date_commencement',
            field=models.DateField(blank=True, null=True, verbose_name='Date de commencement'),
        ),
    ]
