# Generated by Django 2.1.3 on 2018-12-20 18:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('TGA_tool', '0009_auto_20181220_1859'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coach',
            options={'ordering': ['nom'], 'verbose_name': 'coach'},
        ),
        migrations.AlterModelOptions(
            name='eleve',
            options={'ordering': ['nom'], 'verbose_name': 'eleve'},
        ),
        migrations.AlterModelOptions(
            name='parent',
            options={'ordering': ['nom'], 'verbose_name': 'parent'},
        ),
        migrations.AddField(
            model_name='coach',
            name='mail',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='E-mail'),
        ),
        migrations.AddField(
            model_name='coach',
            name='nom',
            field=models.CharField(default='', max_length=42, unique=True, verbose_name='Nom'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coach',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eleve',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='E-mail'),
        ),
        migrations.AddField(
            model_name='eleve',
            name='nom',
            field=models.CharField(default='', max_length=42, unique=True, verbose_name='Nom'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eleve',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='parent',
            name='mail',
            field=models.EmailField(blank=True, max_length=254, unique=True, verbose_name='E-mail'),
        ),
        migrations.AddField(
            model_name='parent',
            name='nom',
            field=models.CharField(default='', max_length=42, unique=True, verbose_name='Nom'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parent',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
