# Generated by Django 2.2 on 2019-04-15 01:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TGA_tool', '0010_auto_20190412_1550'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requete',
            name='creneau',
        ),
        migrations.RemoveField(
            model_name='requete',
            name='jour',
        ),
        migrations.CreateModel(
            name='DateCreneau',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour', models.CharField(blank=True, choices=[('Dimanche', 'Dimanche'), ('Lundi', 'Lundi'), ('Mardi', 'Mardi'), ('Mercredi', 'Mercredi'), ('Jeudi', 'Jeudi'), ('Vendredi', 'Vendredi'), ('Samedi', 'Samedi')], max_length=70, null=True)),
                ('creneau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TGA_tool.Creneau')),
                ('requete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TGA_tool.Requete')),
            ],
        ),
        migrations.AddField(
            model_name='requete',
            name='creneaux',
            field=models.ManyToManyField(blank=True, through='TGA_tool.DateCreneau', to='TGA_tool.Creneau', verbose_name='Créneau'),
        ),
    ]
