# Generated by Django 2.1.3 on 2018-12-20 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TGA_tool', '0010_auto_20181220_1923'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cours',
            name='frequence',
        ),
    ]
