# Generated by Django 2.1.3 on 2018-11-26 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TGA_tool', '0010_enfant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cours',
            fields=[
                ('groupe_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='TGA_tool.Groupe')),
                ('matiere', models.CharField(max_length=14)),
                ('groupe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='niv', to='TGA_tool.Groupe')),
            ],
            bases=('TGA_tool.groupe',),
        ),
        migrations.RemoveField(
            model_name='enfant',
            name='fils',
        ),
        migrations.RemoveField(
            model_name='pere',
            name='fils',
        ),
        migrations.DeleteModel(
            name='Enfant',
        ),
        migrations.DeleteModel(
            name='Fils',
        ),
        migrations.DeleteModel(
            name='pere',
        ),
        migrations.AddField(
            model_name='eleve',
            name='cours',
            field=models.ManyToManyField(limit_choices_to={'cours_set.all()'}, related_name='classe', to='TGA_tool.Cours', verbose_name='Matiere'),
        ),
    ]
