# Generated by Django 2.2 on 2019-04-15 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TGA_tool', '0011_auto_20190415_0333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requete',
            name='client',
        ),
        migrations.RemoveField(
            model_name='requete',
            name='creneaux',
        ),
        migrations.RemoveField(
            model_name='requete',
            name='eleve',
        ),
        migrations.RemoveField(
            model_name='requete',
            name='session',
        ),
        migrations.RemoveField(
            model_name='client',
            name='sessions',
        ),
        migrations.RemoveField(
            model_name='elevepotentiel',
            name='sessions',
        ),
        migrations.DeleteModel(
            name='DateCreneau',
        ),
        migrations.DeleteModel(
            name='Requete',
        ),
    ]
