# Generated by Django 2.1.3 on 2018-11-26 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TGA_tool', '0011_auto_20181126_2303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cours',
            name='groupe',
        ),
        migrations.RemoveField(
            model_name='cours',
            name='groupe_ptr',
        ),
        migrations.RemoveField(
            model_name='eleve',
            name='cours',
        ),
        migrations.DeleteModel(
            name='Cours',
        ),
    ]
