# Generated by Django 2.2 on 2019-04-15 02:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TGA_tool', '0012_auto_20190415_0404'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requete',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TGA_tool.Client')),
                ('eleve', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TGA_tool.ElevePotentiel')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='TGA_tool.Session')),
            ],
        ),
        migrations.CreateModel(
            name='DateCreneau',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour', models.CharField(blank=True, choices=[('Dimanche', 'Dimanche'), ('Lundi', 'Lundi'), ('Mardi', 'Mardi'), ('Mercredi', 'Mercredi'), ('Jeudi', 'Jeudi'), ('Vendredi', 'Vendredi'), ('Samedi', 'Samedi')], max_length=70, null=True)),
                ('creneau', models.ManyToManyField(blank=True, to='TGA_tool.Creneau')),
                ('requete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TGA_tool.Requete', verbose_name='Date_Requete')),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='sessions',
            field=models.ManyToManyField(blank=True, through='TGA_tool.Requete', to='TGA_tool.Session', verbose_name='Cours potentiels demandes'),
        ),
        migrations.AddField(
            model_name='elevepotentiel',
            name='sessions',
            field=models.ManyToManyField(blank=True, through='TGA_tool.Requete', to='TGA_tool.Session', verbose_name='Cours potentiels demandes'),
        ),
    ]
