# Generated by Django 2.1.3 on 2019-01-03 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TGA_tool', '0012_cours_frequence'),
    ]

    operations = [
        migrations.CreateModel(
            name='Famille',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=42, verbose_name='Nom de famille')),
                ('adresse', models.CharField(max_length=42, unique=True, verbose_name='Adresse de famille')),
            ],
            options={
                'verbose_name': 'Famille',
                'ordering': ['nom'],
            },
        ),
        migrations.AlterModelOptions(
            name='matiere',
            options={'ordering': ['-curriculum', 'matiere'], 'verbose_name': 'matiere'},
        ),
        migrations.RenameField(
            model_name='parent',
            old_name='mail',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='parent',
            old_name='num_tel',
            new_name='telephone',
        ),
        migrations.RemoveField(
            model_name='eleve',
            name='parent_resp',
        ),
        migrations.RemoveField(
            model_name='eleve',
            name='parent_sec',
        ),
        migrations.RemoveField(
            model_name='parent',
            name='adresse',
        ),
        migrations.AlterField(
            model_name='eleve',
            name='curriculum',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TGA_tool.Curriculum', verbose_name='Curriculum'),
        ),
        migrations.AlterField(
            model_name='eleve',
            name='email',
            field=models.EmailField(blank=True, help_text='Optionnel', max_length=254, null=True, unique=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='eleve',
            name='num',
            field=models.CharField(blank=True, help_text='Optionnel', max_length=15, null=True, unique=True, verbose_name='Telephone'),
        ),
        migrations.AlterField(
            model_name='frequence',
            name='creneau',
            field=models.ForeignKey(blank=True, help_text='Créneau dans la journée', null=True, on_delete=django.db.models.deletion.SET_NULL, to='TGA_tool.Creneau', verbose_name='Creneau'),
        ),
        migrations.AlterField(
            model_name='frequence',
            name='date_debut',
            field=models.DateField(blank=True, help_text='Date du début du cours', null=True, verbose_name='Debut du cours'),
        ),
        migrations.AlterField(
            model_name='frequence',
            name='date_limite',
            field=models.DateField(blank=True, help_text='Date de la fin du cours', null=True, verbose_name='Fin du cours'),
        ),
        migrations.AlterField(
            model_name='frequence',
            name='day_of_month',
            field=models.PositiveIntegerField(blank=True, help_text="Pour les fréquences: Chaque mois et ''Chaque X mois' ", null=True, verbose_name='Jour du mois'),
        ),
        migrations.AlterField(
            model_name='frequence',
            name='frequence',
            field=models.CharField(choices=[('Frequence', (('Une seance', 'Une séance'), ('Chaque jour', 'Chaque jour'), ('Un jour chaque semaine', 'Chaque semaine'), ('Un jour chaque mois', 'Chaque mois'))), ('Personalisé', (('Jours', 'Chaque X jours'), ('Semaines', 'Chaque X semaines'), ('Mois', 'Chaque X mois')))], default='Une seance', max_length=30, verbose_name='Fréquence'),
        ),
        migrations.AlterField(
            model_name='frequence',
            name='jour',
            field=models.PositiveIntegerField(blank=True, choices=[(7, 'Dimanche'), (1, 'Lundi'), (2, 'Mardi'), (3, 'Mercredi'), (4, 'Jeudi'), (5, 'Vendredi'), (6, 'Samedi')], help_text="Pour les fréquences: ''Chaque semaine'' et ''Chaque X semaines''", null=True, verbose_name='Jour de la semaine'),
        ),
        migrations.AlterField(
            model_name='frequence',
            name='period',
            field=models.PositiveIntegerField(blank=True, help_text='Chaque X jours/semaines/mois', null=True, verbose_name='Période'),
        ),
        migrations.AlterField(
            model_name='matiere',
            name='matiere',
            field=models.CharField(choices=[('Mathématiques', 'Mathématiques'), ('Physique', 'Physique'), ('SVT', 'SVT'), ('Français', 'Français'), ('Anglais', 'Anglais'), ('Technologie', 'Technologie'), ('SES', 'SES'), ('Philosophie', 'Philosophie')], max_length=16, verbose_name='Matiere'),
        ),
        migrations.AlterField(
            model_name='parent',
            name='estResponsable',
            field=models.BooleanField(verbose_name='Responsable des enfants'),
        ),
        migrations.AddField(
            model_name='eleve',
            name='famille',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='TGA_tool.Famille', verbose_name="Famille de l'élève"),
        ),
        migrations.AddField(
            model_name='parent',
            name='famille',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='TGA_tool.Famille', verbose_name='Famille du parent'),
        ),
    ]
