# Generated by Django 2.1.3 on 2018-11-26 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TGA_tool', '0012_auto_20181126_2310'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matiere', models.CharField(max_length=14)),
                ('groupe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='niv', to='TGA_tool.Groupe')),
            ],
        ),
        migrations.AddField(
            model_name='eleve',
            name='cours',
            field=models.ManyToManyField(limit_choices_to={'cours_set.all()'}, related_name='classe', to='TGA_tool.Cours', verbose_name='Matiere'),
        ),
    ]
