# Generated by Django 2.1.3 on 2018-11-26 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TGA_tool', '0013_auto_20181126_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eleve',
            name='cours',
            field=models.ManyToManyField(limit_choices_to={'cours_set.all().id'}, related_name='classe', to='TGA_tool.Cours', verbose_name='Matiere'),
        ),
    ]
