# Generated by Django 2.1.3 on 2019-01-04 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TGA_tool', '0013_auto_20190103_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='genre',
            field=models.CharField(choices=[('M.', 'Monsieur'), ('Mme.', 'Madame'), ('Mlle', 'Mademoiselle')], default='M.', max_length=10, verbose_name='Civilité'),
        ),
        migrations.AddField(
            model_name='parent',
            name='prenom',
            field=models.CharField(default='', max_length=42, verbose_name='Prénom'),
        ),
        migrations.AlterField(
            model_name='eleve',
            name='famille',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='TGA_tool.Famille', verbose_name='Famille - adresse'),
        ),
        migrations.AlterField(
            model_name='parent',
            name='estResponsable',
            field=models.BooleanField(default=False, verbose_name='Responsable des enfants'),
        ),
        migrations.AlterField(
            model_name='parent',
            name='famille',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='TGA_tool.Famille', verbose_name='Famille - adresse'),
        ),
        migrations.AlterField(
            model_name='parent',
            name='nom',
            field=models.CharField(max_length=42, verbose_name='Nom'),
        ),
    ]
