# Generated by Django 2.2 on 2019-04-18 00:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TGA_tool', '0013_auto_20190415_0442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datecreneau',
            name='requete',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TGA_tool.Requete', verbose_name='Requete'),
        ),
        migrations.AlterField(
            model_name='payement',
            name='date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date et heure'),
        ),
    ]
