# Generated by Django 2.1.3 on 2018-11-27 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TGA_tool', '0014_auto_20181127_0021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eleve',
            name='cours',
            field=models.ManyToManyField(related_name='classe', to='TGA_tool.Cours', verbose_name='Matiere'),
        ),
    ]
