# Generated by Django 2.2 on 2019-04-18 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TGA_tool', '0014_auto_20190418_0238'),
    ]

    operations = [
        migrations.AddField(
            model_name='seance_cours',
            name='clients',
            field=models.ManyToManyField(blank=True, to='TGA_tool.Client', verbose_name='presence'),
        ),
        migrations.AlterField(
            model_name='parent',
            name='genre',
            field=models.CharField(choices=[('Mr.', 'Monsieur'), ('Mme.', 'Madame'), ('Mlle', 'Mademoiselle')], default='M.', max_length=10, verbose_name='Civilité'),
        ),
    ]
