# Generated by Django 2.1.3 on 2019-01-04 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TGA_tool', '0014_auto_20190104_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eleve',
            name='famille',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='TGA_tool.Famille', verbose_name='Famille - adresse'),
        ),
        migrations.AlterField(
            model_name='parent',
            name='estResponsable',
            field=models.BooleanField(default=False, verbose_name='Parent principal'),
        ),
        migrations.AlterField(
            model_name='parent',
            name='famille',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='TGA_tool.Famille', verbose_name='Famille - adresse'),
        ),
    ]
