# Generated by Django 2.1.3 on 2018-11-27 01:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TGA_tool', '0015_auto_20181127_0105'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=42, unique=True, verbose_name='Nom')),
                ('telphone', models.CharField(max_length=15, unique=True, verbose_name='Telephone')),
                ('mail', models.EmailField(max_length=254, verbose_name='E-mail')),
            ],
        ),
        migrations.CreateModel(
            name='Salle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=42, unique=True, verbose_name='Nom')),
                ('capcite', models.PositiveIntegerField(verbose_name='Capacité')),
                ('ecran', models.BooleanField(verbose_name='Posséde un écean')),
                ('batiment', models.BooleanField(verbose_name='TGA')),
            ],
        ),
        migrations.CreateModel(
            name='Seance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coach', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='TGA_tool.Coach', verbose_name='Coach')),
            ],
        ),
        migrations.AlterModelOptions(
            name='cours',
            options={'verbose_name': 'cours'},
        ),
        migrations.AddField(
            model_name='parent',
            name='dz',
            field=models.BooleanField(default=False, verbose_name='Programme Algérien'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cours',
            name='groupe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='niv', to='TGA_tool.Groupe', verbose_name='Groupe'),
        ),
        migrations.AlterField(
            model_name='cours',
            name='matiere',
            field=models.CharField(max_length=14, unique=True, verbose_name='Matiere'),
        ),
        migrations.AlterField(
            model_name='eleve',
            name='date_naissance',
            field=models.DateField(null=True, verbose_name='Date de naissance'),
        ),
        migrations.AlterField(
            model_name='eleve',
            name='groupe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TGA_tool.Groupe', verbose_name='Groupe'),
        ),
        migrations.AlterField(
            model_name='eleve',
            name='nom_et',
            field=models.CharField(max_length=42, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='eleve',
            name='num',
            field=models.CharField(max_length=15, null=True, verbose_name='Telephone'),
        ),
        migrations.AlterField(
            model_name='parent',
            name='adresse',
            field=models.CharField(max_length=150, unique=True, verbose_name='Adresse'),
        ),
        migrations.AlterField(
            model_name='parent',
            name='estResponsable',
            field=models.BooleanField(verbose_name="Responsable de l'enfant"),
        ),
        migrations.AlterField(
            model_name='parent',
            name='mail',
            field=models.EmailField(max_length=254, unique=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='parent',
            name='nom',
            field=models.CharField(max_length=42, unique=True, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='parent',
            name='num_tel',
            field=models.CharField(max_length=15, unique=True, verbose_name='Telephone'),
        ),
        migrations.AddField(
            model_name='seance',
            name='cours',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='TGA_tool.Cours', verbose_name='Cours'),
        ),
        migrations.AddField(
            model_name='seance',
            name='salle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='TGA_tool.Salle', verbose_name='Salle'),
        ),
    ]
