# Generated by Django 2.2 on 2019-04-20 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TGA_tool', '0015_auto_20190418_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='cours',
            name='vip',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
