# Generated by Django 2.1.3 on 2019-01-04 23:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TGA_tool', '0015_auto_20190104_2349'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coach',
            old_name='disponibilité',
            new_name='disponibilite',
        ),
        migrations.RenameField(
            model_name='coach',
            old_name='mail',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='coach',
            old_name='telphone',
            new_name='telephone',
        ),
        migrations.RenameField(
            model_name='salle',
            old_name='disponibilité',
            new_name='disponibilite',
        ),
        migrations.AddField(
            model_name='coach',
            name='genre',
            field=models.CharField(choices=[('M.', 'Monsieur'), ('Mme.', 'Madame'), ('Mlle', 'Mademoiselle')], default='M.', max_length=10, verbose_name='Civilité'),
        ),
        migrations.AddField(
            model_name='coach',
            name='prenom',
            field=models.CharField(default='', max_length=42, unique=True, verbose_name='Prénom'),
        ),
        migrations.AlterField(
            model_name='coach',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
