# Generated by Django 2.1.3 on 2018-11-27 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TGA_tool', '0016_auto_20181127_0220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parent',
            name='dz',
        ),
    ]
