# Generated by Django 2.1.5 on 2019-01-27 12:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TGA_tool', '0016_auto_20190105_0017'),
    ]

    operations = [
        migrations.AddField(
            model_name='seance_cours',
            name='eleves',
            field=models.ManyToManyField(related_name='presence', to='TGA_tool.Eleve'),
        ),
        migrations.AlterField(
            model_name='coach',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='matiere',
            name='matiere',
            field=models.CharField(choices=[('Mathematiques', 'Mathematiques'), ('Physique', 'Physique'), ('SVT', 'SVT'), ('Français', 'Français'), ('Anglais', 'Anglais'), ('Technologie', 'Technologie'), ('SES', 'SES'), ('Philosophie', 'Philosophie')], max_length=16, verbose_name='Matiere'),
        ),
        migrations.AlterField(
            model_name='seance_cours',
            name='statut',
            field=models.CharField(choices=[('Planifié', 'Planifiée'), ('Done', 'Effectué'), ('Annulé', 'Annulée')], default='PL', max_length=2, verbose_name='Statut'),
        ),
    ]
