# Generated by Django 2.1.3 on 2018-11-27 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TGA_tool', '0017_remove_parent_dz'),
    ]

    operations = [
        migrations.AddField(
            model_name='eleve',
            name='dz',
            field=models.BooleanField(default=False, verbose_name='Programme Algérien'),
            preserve_default=False,
        ),
    ]
