# Generated by Django 2.1.3 on 2019-01-30 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TGA_tool', '0017_auto_20190127_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='seance_coaching',
            name='coach',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='TGA_tool.Coach', verbose_name='Coach'),
        ),
    ]
