# Generated by Django 2.2 on 2019-04-21 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TGA_tool', '0017_auto_20190421_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='frequence',
            name='jour_two',
            field=models.PositiveIntegerField(blank=True, choices=[(7, 'Dimanche'), (1, 'Lundi'), (2, 'Mardi'), (3, 'Mercredi'), (4, 'Jeudi'), (5, 'Vendredi'), (6, 'Samedi')], null=True, verbose_name='Deuxième jour de la semaine'),
        ),
        migrations.AlterField(
            model_name='frequence',
            name='frequence',
            field=models.CharField(choices=[('Frequence', (('Une seance', 'Une séance'), ('Chaque jour', 'Chaque jour'), ('Un jour chaque semaine', 'Chaque semaine'), ('Deux fois par semaine', 'Deux fois par semaine'), ('Un jour chaque mois', 'Chaque mois'))), ('Personalisé', (('Jours', 'Chaque X jours'), ('Semaines', 'Chaque X semaines'), ('Mois', 'Chaque X mois')))], default='Une seance', max_length=30, verbose_name='Fréquence'),
        ),
        migrations.AlterField(
            model_name='frequence',
            name='jour',
            field=models.PositiveIntegerField(blank=True, choices=[(7, 'Dimanche'), (1, 'Lundi'), (2, 'Mardi'), (3, 'Mercredi'), (4, 'Jeudi'), (5, 'Vendredi'), (6, 'Samedi')], null=True, verbose_name='Jour de la semaine'),
        ),
    ]
