# Generated by Django 2.1.3 on 2018-11-27 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TGA_tool', '0018_eleve_dz'),
    ]

    operations = [
        migrations.AddField(
            model_name='eleve',
            name='date_inscription',
            field=models.DateField(auto_now=True, verbose_name="Date d'inscription"),
        ),
    ]
