# Generated by Django 2.2 on 2019-04-22 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TGA_tool', '0018_auto_20190422_0015'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prospect_courses',
            fields=[
                ('requete_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='TGA_tool.Requete')),
                ('date_fin', models.DateField(verbose_name='Date fin de la requete ')),
            ],
            options={
                'ordering': ['date_fin'],
                'verbose_name': 'Requetes',
            },
            bases=('TGA_tool.requete',),
        ),
        migrations.AlterModelOptions(
            name='requete',
            options={'verbose_name': 'Requetes VIP'},
        ),
    ]
