# Generated by Django 2.1.3 on 2019-01-30 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TGA_tool', '0018_seance_coaching_coach'),
    ]

    operations = [
        migrations.AddField(
            model_name='seance_coaching',
            name='statut',
            field=models.CharField(choices=[('Planifié', 'Planifiée'), ('Done', 'Effectué'), ('Annulé', 'Annulée')], default='PL', max_length=2, verbose_name='Statut'),
        ),
    ]
