# Generated by Django 2.1.3 on 2018-11-27 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TGA_tool', '0019_eleve_date_inscription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eleve',
            name='cours',
        ),
        migrations.RemoveField(
            model_name='seance',
            name='coach',
        ),
        migrations.RemoveField(
            model_name='seance',
            name='salle',
        ),
        migrations.DeleteModel(
            name='Coach',
        ),
        migrations.DeleteModel(
            name='Salle',
        ),
    ]
