# Generated by Django 2.1.3 on 2019-01-31 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TGA_tool', '0019_seance_coaching_statut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seance_coaching',
            name='statut',
            field=models.CharField(choices=[('Planifié', 'Planifiée'), ('Done', 'Effectué'), ('Annulé', 'Annulée')], default='PL', max_length=8, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='seance_cours',
            name='statut',
            field=models.CharField(choices=[('Planifié', 'Planifiée'), ('Done', 'Effectué'), ('Annulé', 'Annulée')], default='PL', max_length=8, verbose_name='Statut'),
        ),
    ]
