# Generated by Django 2.2 on 2019-04-23 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TGA_tool', '0019_auto_20190422_1450'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='sessions',
        ),
        migrations.RemoveField(
            model_name='requete',
            name='client',
        ),
        migrations.AddField(
            model_name='parent',
            name='sessions',
            field=models.ManyToManyField(blank=True, through='TGA_tool.Requete', to='TGA_tool.Session', verbose_name='Cours potentiels demandes'),
        ),
        migrations.AddField(
            model_name='requete',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TGA_tool.Parent'),
        ),
    ]
