# Generated by Django 2.1.5 on 2019-02-01 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TGA_tool', '0018_payement'),
        ('TGA_tool', '0020_auto_20190131_0144'),
    ]

    operations = [
    ]
