# Generated by Django 2.1.3 on 2018-11-27 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TGA_tool', '0020_auto_20181127_1249'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disponibilité', models.CharField(max_length=15)),
                ('nom', models.CharField(max_length=42, unique=True, verbose_name='Nom')),
                ('telphone', models.CharField(max_length=15, unique=True, verbose_name='Telephone')),
                ('mail', models.EmailField(max_length=254, verbose_name='E-mail')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Salle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disponibilité', models.CharField(max_length=15)),
                ('nom', models.CharField(max_length=42, unique=True, verbose_name='Nom')),
                ('capcite', models.PositiveIntegerField(verbose_name='Capacité')),
                ('ecran', models.BooleanField(verbose_name='Posséde un écean')),
                ('batiment', models.BooleanField(verbose_name='TGA')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='eleve',
            name='cours',
            field=models.ManyToManyField(related_name='classe', to='TGA_tool.Cours', verbose_name='Matiere'),
        ),
        migrations.AddField(
            model_name='seance',
            name='coach',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='TGA_tool.Coach', verbose_name='Coach'),
        ),
        migrations.AddField(
            model_name='seance',
            name='salle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='TGA_tool.Salle', verbose_name='Salle'),
        ),
    ]
