# Generated by Django 2.1.3 on 2019-02-01 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TGA_tool', '0020_auto_20190131_0144'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Date')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=8)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TGA_tool.Parent', verbose_name='Parent payeur')),
            ],
            options={
                'verbose_name': 'Paiement',
            },
        ),
    ]
