# Generated by Django 2.2 on 2019-04-25 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TGA_tool', '0021_auto_20190425_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cours',
            name='match_indic',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
