# Generated by Django 2.1.3 on 2018-11-27 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TGA_tool', '0022_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='date',
            field=models.DurationField(),
        ),
    ]
