# Generated by Django 2.2 on 2019-05-02 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TGA_tool', '0022_auto_20190425_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='sessions',
            field=models.ManyToManyField(blank=True, help_text='Les matières que peut enseigner ce coach', related_name='enseigne', to='TGA_tool.Session', verbose_name='sessions'),
        ),
    ]
