# Generated by Django 2.1.3 on 2019-02-01 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TGA_tool', '0019_seance_coaching_statut'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='salaire',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
