# Generated by Django 2.2 on 2019-05-02 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TGA_tool', '0023_auto_20190502_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seance_coaching',
            name='statut',
            field=models.CharField(choices=[('Planifié', 'Planifiée'), ('Effectué', 'Effectué'), ('Annulé', 'Annulée')], default='Planifié', max_length=15, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='seance_cours',
            name='statut',
            field=models.CharField(choices=[('Planifié', 'Planifiée'), ('Effectué', 'Effectué'), ('Annulé', 'Annulée')], default='Planifié', max_length=15, verbose_name='Statut'),
        ),
    ]
