# Generated by Django 2.1.3 on 2019-02-02 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TGA_tool', '0023_coach_salaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='solde',
            field=models.IntegerField(default=0),
        ),
    ]
