# Generated by Django 2.1.3 on 2018-11-28 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TGA_tool', '0024_auto_20181128_1114'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eleve',
            old_name='nom_et',
            new_name='nom',
        ),
        migrations.AlterField(
            model_name='cours',
            name='matiere',
            field=models.CharField(max_length=14, verbose_name='Matiere'),
        ),
        migrations.AlterField(
            model_name='eleve',
            name='parent_sec',
            field=models.ForeignKey(blank=True, limit_choices_to={'estResponsable': False}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secondaire', to='TGA_tool.Parent', verbose_name='Parent contact'),
        ),
        migrations.AlterField(
            model_name='parent',
            name='adresse',
            field=models.CharField(max_length=150, verbose_name='Adresse'),
        ),
    ]
