# Generated by Django 2.1.3 on 2018-11-28 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TGA_tool', '0025_auto_20181128_1533'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapitre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapitre', models.CharField(max_length=50)),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TGA_tool.Cours', verbose_name='Matiere')),
            ],
        ),
        migrations.CreateModel(
            name='Notions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notion', models.CharField(max_length=50, verbose_name='Notion')),
                ('details', models.TextField(blank=True, null=True, verbose_name='Details')),
            ],
        ),
        migrations.AddField(
            model_name='seance',
            name='chapitre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='TGA_tool.Chapitre', verbose_name='Chapitre'),
        ),
        migrations.AddField(
            model_name='seance',
            name='notions',
            field=models.ManyToManyField(related_name='Titre', to='TGA_tool.Notions', verbose_name='Notions'),
        ),
    ]
