# Generated by Django 2.1.3 on 2019-02-05 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TGA_tool', '0025_auto_20190202_1746'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElevePotentiel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=42, verbose_name='Prenom')),
                ('num', models.CharField(blank=True, max_length=15, null=True, unique=True, verbose_name='Telephone')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='E-mail')),
            ],
        ),
        migrations.CreateModel(
            name='Payement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Date')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
            options={
                'verbose_name': 'Paiement',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Requete',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Jour', models.CharField(blank=True, choices=[('Dimanche', 'Dimanche'), ('Lundi', 'Lundi'), ('Mardi', 'Mardi'), ('Mercredi', 'Mercredi'), ('Jeudi', 'Jeudi'), ('Vendredi', 'Vendredi'), ('Samedi', 'Samedi')], max_length=10, null=True)),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TGA_tool.ElevePotentiel')),
                ('matiere', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='TGA_tool.Matiere')),
            ],
        ),
        migrations.AlterField(
            model_name='eleve',
            name='famille',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='TGA_tool.Famille', verbose_name='Famille'),
        ),
        migrations.AlterField(
            model_name='eleve',
            name='nom',
            field=models.CharField(max_length=42, verbose_name='Prenom'),
        ),
        migrations.AlterField(
            model_name='parent',
            name='famille',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='TGA_tool.Famille', verbose_name='Famille'),
        ),
        migrations.AddField(
            model_name='payement',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TGA_tool.Parent', verbose_name='Parent payeur'),
        ),
        migrations.AddField(
            model_name='elevepotentiel',
            name='matieres',
            field=models.ManyToManyField(through='TGA_tool.Requete', to='TGA_tool.Matiere', verbose_name='Cours potentiels demandes'),
        ),
    ]
