# Generated by Django 2.2 on 2019-05-05 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TGA_tool', '0025_auto_20190504_1556'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parent',
            name='profession',
        ),
        migrations.AddField(
            model_name='elevepotentiel',
            name='communication',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Comment avez-vous connu TGA ?'),
        ),
        migrations.AddField(
            model_name='parent',
            name='communication',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Comment avez-vous connu TGA ?'),
        ),
        migrations.AddField(
            model_name='parent',
            name='secteur',
            field=models.CharField(blank=True, max_length=100, verbose_name='Secteur'),
        ),
        migrations.AlterField(
            model_name='seance_coaching',
            name='statut',
            field=models.CharField(choices=[('Planifié', 'Planifiée'), ('Effectué', 'Effectué'), ('Annulé', 'Annulée')], default='Planifié', max_length=8, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='seance_cours',
            name='statut',
            field=models.CharField(choices=[('Planifié', 'Planifiée'), ('Effectué', 'Effectué'), ('Annulé', 'Annulée')], default='Planifié', max_length=8, verbose_name='Statut'),
        ),
    ]
