# Generated by Django 2.1.3 on 2018-11-28 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TGA_tool', '0026_auto_20181128_1748'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chapitre',
            options={'verbose_name': 'chapitre'},
        ),
        migrations.AlterModelOptions(
            name='coach',
            options={'verbose_name': 'coach'},
        ),
        migrations.AlterModelOptions(
            name='salle',
            options={'verbose_name': 'salle'},
        ),
        migrations.AlterModelOptions(
            name='seance',
            options={'verbose_name': 'seance'},
        ),
        migrations.RemoveField(
            model_name='seance',
            name='notions',
        ),
        migrations.AlterField(
            model_name='eleve',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='eleve',
            name='num',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Telephone'),
        ),
        migrations.DeleteModel(
            name='Notions',
        ),
    ]
