# Generated by Django 2.2 on 2019-05-06 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TGA_tool', '0026_auto_20190505_0312'),
    ]

    operations = [
        migrations.AddField(
            model_name='requete',
            name='communication',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Comment avez-vous connu TGA ?'),
        ),
    ]
