# Generated by Django 2.1.3 on 2018-11-28 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TGA_tool', '0027_auto_20181128_1908'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notion', models.CharField(max_length=50, verbose_name='Notion')),
                ('details', models.TextField(blank=True, null=True, verbose_name='Details')),
                ('chapitre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TGA_tool.Chapitre')),
            ],
            options={
                'verbose_name': 'notions',
            },
        ),
        migrations.AddField(
            model_name='seance',
            name='notions',
            field=models.ManyToManyField(related_name='Titre', to='TGA_tool.Notions', verbose_name='Notions'),
        ),
    ]
