# Generated by Django 2.1.3 on 2019-02-05 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TGA_tool', '0028_requete_creneau'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elevepotentiel',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='E-mail'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='elevepotentiel',
            name='num',
            field=models.CharField(blank=True, default='', max_length=15, verbose_name='Telephone'),
            preserve_default=False,
        ),
    ]
