# Generated by Django 2.1.3 on 2018-11-28 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TGA_tool', '0028_auto_20181128_1909'),
    ]

    operations = [
        migrations.AddField(
            model_name='seance',
            name='creneau',
            field=models.CharField(default='', max_length=10, null=True),
        ),
    ]
