# Generated by Django 2.2 on 2019-06-17 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TGA_tool', '0028_auto_20190508_0357'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='summer_camp',
            field=models.BooleanField(default=False, verbose_name='Summer Camp'),
        ),
        migrations.AlterField(
            model_name='frequence',
            name='frequence',
            field=models.CharField(choices=[('Frequence', (('Summer Camp', 'Summer Camp'), ('Une seance', 'Une séance'), ('Chaque jour', 'Chaque jour'), ('Un jour chaque semaine', 'Chaque semaine'), ('Deux fois par semaine', 'Deux fois par semaine'), ('Trois fois par semaine', 'Trois fois par semaine'), ('Un jour chaque mois', 'Chaque mois'))), ('Personalisé', (('Jours', 'Chaque X jours'), ('Semaines', 'Chaque X semaines'), ('Mois', 'Chaque X mois')))], default='Une seance', max_length=30, verbose_name='Fréquence'),
        ),
    ]
