# Generated by Django 2.1.3 on 2018-11-29 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TGA_tool', '0029_seance_creneau'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seance',
            name='chapitre',
        ),
        migrations.RemoveField(
            model_name='seance',
            name='coach',
        ),
        migrations.RemoveField(
            model_name='seance',
            name='cours',
        ),
        migrations.RemoveField(
            model_name='seance',
            name='notions',
        ),
        migrations.RemoveField(
            model_name='seance',
            name='salle',
        ),
        migrations.DeleteModel(
            name='Seance',
        ),
    ]
