# Generated by Django 2.1.3 on 2019-02-05 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TGA_tool', '0029_auto_20190205_1848'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requete',
            name='Jour',
        ),
        migrations.AddField(
            model_name='requete',
            name='jour',
            field=models.CharField(blank=True, choices=[('Dimanche', 'Dimanche'), ('Lundi', 'Lundi'), ('Mardi', 'Mardi'), ('Mercredi', 'Mercredi'), ('Jeudi', 'Jeudi'), ('Vendredi', 'Vendredi'), ('Samedi', 'Samedi')], max_length=70, null=True),
        ),
    ]
