# Generated by Django 2.1.3 on 2018-11-29 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TGA_tool', '0030_auto_20181129_1107'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creneau', models.DateTimeField(auto_now=True, verbose_name='Creneau')),
                ('chapitre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='TGA_tool.Chapitre', verbose_name='Chapitre')),
                ('coach', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='TGA_tool.Coach', verbose_name='Coach')),
                ('cours', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='TGA_tool.Cours', verbose_name='Cours')),
                ('notions', models.ManyToManyField(related_name='Titre', to='TGA_tool.Notions', verbose_name='Notions')),
                ('salle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='TGA_tool.Salle', verbose_name='Salle')),
            ],
            options={
                'verbose_name': 'seance',
            },
        ),
    ]
