# Generated by Django 2.1.3 on 2019-02-05 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TGA_tool', '0030_auto_20190205_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elevepotentiel',
            name='matieres',
            field=models.ManyToManyField(blank=True, through='TGA_tool.Requete', to='TGA_tool.Matiere', verbose_name='Cours potentiels demandes'),
        ),
    ]
