# Generated by Django 2.1.3 on 2018-11-29 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TGA_tool', '0031_seance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seance',
            name='chapitre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='TGA_tool.Chapitre', verbose_name='Chapitre'),
        ),
        migrations.AlterField(
            model_name='seance',
            name='coach',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='TGA_tool.Coach', verbose_name='Coach'),
        ),
        migrations.AlterField(
            model_name='seance',
            name='creneau',
            field=models.DateTimeField(verbose_name='Creneau'),
        ),
        migrations.AlterField(
            model_name='seance',
            name='notions',
            field=models.ManyToManyField(blank=True, related_name='Titre', to='TGA_tool.Notions', verbose_name='Notions'),
        ),
        migrations.AlterField(
            model_name='seance',
            name='salle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='TGA_tool.Salle', verbose_name='Salle'),
        ),
    ]
