# Generated by Django 2.1.3 on 2018-12-01 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TGA_tool', '0032_auto_20181129_1820'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapitre',
            name='matiere',
        ),
        migrations.RemoveField(
            model_name='cours',
            name='groupe',
        ),
        migrations.RemoveField(
            model_name='notions',
            name='chapitre',
        ),
        migrations.RemoveField(
            model_name='seance',
            name='chapitre',
        ),
        migrations.RemoveField(
            model_name='seance',
            name='coach',
        ),
        migrations.RemoveField(
            model_name='seance',
            name='cours',
        ),
        migrations.RemoveField(
            model_name='seance',
            name='notions',
        ),
        migrations.RemoveField(
            model_name='seance',
            name='salle',
        ),
        migrations.DeleteModel(
            name='test',
        ),
        migrations.RemoveField(
            model_name='eleve',
            name='cours',
        ),
        migrations.RemoveField(
            model_name='eleve',
            name='dz',
        ),
        migrations.RemoveField(
            model_name='eleve',
            name='groupe',
        ),
        migrations.DeleteModel(
            name='Chapitre',
        ),
        migrations.DeleteModel(
            name='Coach',
        ),
        migrations.DeleteModel(
            name='Cours',
        ),
        migrations.DeleteModel(
            name='Groupe',
        ),
        migrations.DeleteModel(
            name='Notions',
        ),
        migrations.DeleteModel(
            name='Salle',
        ),
        migrations.DeleteModel(
            name='Seance',
        ),
    ]
