# Generated by Django 2.1.3 on 2019-02-05 21:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('TGA_tool', '0034_auto_20190205_2207'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eleve',
            fields=[
                ('elevepotentiel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='TGA_tool.ElevePotentiel')),
                ('date_naissance', models.DateField(blank=True, null=True, verbose_name='Date de naissance')),
                ('etablissement', models.CharField(blank=True, max_length=20, null=True)),
                ('date_inscription', models.DateField(auto_now=True, verbose_name="Date d'inscription")),
                ('cours', models.ManyToManyField(blank=True, related_name='cours', to='TGA_tool.Cours', verbose_name='Cours')),
                ('curriculum', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TGA_tool.Curriculum', verbose_name='Curriculum')),
                ('famille', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='TGA_tool.Famille', verbose_name='Famille')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'eleve',
                'ordering': ['nom'],
            },
            bases=('TGA_tool.elevepotentiel',),
        ),
        migrations.AddField(
            model_name='seance_coaching',
            name='eleve',
            field=models.ManyToManyField(blank=True, related_name='eleve_coaching', to='TGA_tool.Eleve'),
        ),
        migrations.AddField(
            model_name='seance_cours',
            name='eleves',
            field=models.ManyToManyField(related_name='presence', to='TGA_tool.Eleve'),
        ),
    ]
