# Generated by Django 2.1.3 on 2019-02-05 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TGA_tool', '0035_auto_20190205_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='credit',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='parent',
            name='debit',
            field=models.IntegerField(default=0),
        ),
    ]
