# Generated by Django 2.1.3 on 2019-02-05 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TGA_tool', '0036_auto_20190205_2329'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='grade',
            field=models.CharField(blank=True, choices=[('Junior', 'Junior'), ('Senior', 'Senior'), ('Excellence', 'Excellence')], default='', max_length=10),
        ),
    ]
