# Generated by Django 2.1.3 on 2019-02-11 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TGA_tool', '0038_auto_20190209_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='nom',
            field=models.CharField(max_length=42, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='coach',
            name='prenom',
            field=models.CharField(default='', max_length=42, verbose_name='Prénom'),
        ),
    ]
