# Generated by Django 2.1.3 on 2019-02-11 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TGA_tool', '0039_auto_20190211_0217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matiere',
            name='matiere',
            field=models.CharField(max_length=30, verbose_name='Matiere'),
        ),
    ]
